In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)

In [3]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [6]:
# Group by Category and calculate the sum of Sales
cat = df.groupby('Category')['Sales'].sum()
cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [7]:
# Group by Store and calculate the sum of Sales
df.groupby('Store')['Sales'].sum()

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [9]:
# Group by multiple columns
# Group by Category and Store
df.groupby(['Category','Store'])['Sales'].sum()

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

In [12]:
# Aggregation
df['Sales'].mean()
"""mean median min max count std """

'mean median min max count std '

In [14]:
df['Sales'].agg(['sum', 'mean', 'min', 'max', 'count', 'std', 'median'])
# mode cannot be calculated

sum       1500.000000
mean       187.500000
min        100.000000
max        300.000000
count        8.000000
std         66.062741
median     190.000000
Name: Sales, dtype: float64

In [15]:
# -------------------------------     pivot table       --------------------------------------

In [17]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)
df

         Date Product Region  Sales  Units    Rep
0  2023-01-01       A   East    300     58   John
1  2023-01-02       B   West    986     37   Mary
2  2023-01-03       C  North    645     23    Bob
3  2023-01-04       D  South    723     42  Alice
4  2023-01-05       A   East    629     51   John
5  2023-01-06       B   West    844     38   Mary
6  2023-01-07       C  North    623     15    Bob
7  2023-01-08       D  South    539     28  Alice
8  2023-01-09       A   East    994     16   John
9  2023-01-10       B   West    386     58   Mary
10 2023-01-11       C  North    189     59    Bob
11 2023-01-12       D  South    205     65  Alice
12 2023-01-13       A   East    313     87   John
13 2023-01-14       B   West    843     38   Mary
14 2023-01-15       C  North    569     37    Bob
15 2023-01-16       D  South    287     55  Alice
16 2023-01-17       A   East    941     84   John
17 2023-01-18       B   West    212     28   Mary
18 2023-01-19       C  North    777     18    Bob
19 2023-01-20       D  South    227     56  Alice

In [18]:
df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    300     58   John  January      Q1
1  2023-01-02       B   West    986     37   Mary  January      Q1
2  2023-01-03       C  North    645     23    Bob  January      Q1
3  2023-01-04       D  South    723     42  Alice  January      Q1
4  2023-01-05       A   East    629     51   John  January      Q1
5  2023-01-06       B   West    844     38   Mary  January      Q1
6  2023-01-07       C  North    623     15    Bob  January      Q1
7  2023-01-08       D  South    539     28  Alice  January      Q1
8  2023-01-09       A   East    994     16   John  January      Q1
9  2023-01-10       B   West    386     58   Mary  January      Q1
10 2023-01-11       C  North    189     59    Bob  January      Q1
11 2023-01-12       D  South    205     65  Alice  January      Q1
12 2023-01-13       A   East    313     87   John  January      Q1
13 2023-01-14       B   West    843     38   Mary  January      Q1
14 2023-01-15       C  North    569     37    Bob  January      Q1
15 2023-01-16       D  South    287     55  Alice  January      Q1
16 2023-01-17       A   East    941     84   John  January      Q1
17 2023-01-18       B   West    212     28   Mary  January      Q1
18 2023-01-19       C  North    777     18    Bob  January      Q1
19 2023-01-20       D  South    227     56  Alice  January      Q1

In [19]:
pd.pivot_table(df,values = "Sales",index = 'Region',columns="Product",aggfunc = 'median')

Product      A      B      C      D
Region
East     629.0    NaN    NaN    NaN
North      NaN    NaN  623.0    NaN
South      NaN    NaN    NaN  287.0
West       NaN  843.0    NaN    NaN

In [24]:
pd.pivot_table(df,values = ['Sales','Units'],index = 'Region',columns='Product',aggfunc='max')

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     994.0    NaN    NaN    NaN  87.0   NaN   NaN   NaN
North      NaN    NaN  777.0    NaN   NaN   NaN  59.0   NaN
South      NaN    NaN    NaN  723.0   NaN   NaN   NaN  65.0
West       NaN  986.0    NaN    NaN   NaN  58.0   NaN   NaN

In [25]:
pd.crosstab(df['Region'],df['Product'])
# default vaues are frequency

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

In [30]:
pd.crosstab(df['Region'],df['Product'],values = df['Sales'],aggfunc='max')

Product      A      B      C      D
Region
East     994.0    NaN    NaN    NaN
North      NaN    NaN  777.0    NaN
South      NaN    NaN    NaN  723.0
West       NaN  986.0    NaN    NaN

In [31]:
# --------------------------------     operations     -------------------------

In [46]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [47]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [34]:
df1.shape

(5, 3)

In [35]:
df1.columns

Index(['A', 'B', 'C'], dtype='str')

In [36]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [37]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [38]:
df1['A'] + 10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

In [39]:
def square(x):
    # return x**2

In [48]:
df1['D'] = df1['B'].apply(square)

In [49]:
df1

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500