In [1]:
import numpy as np
import pandas as pd

In [2]:
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {1:10,2:20,3:30}

In [3]:
pd.Series(my_list,index = labels)

a    10
b    20
c    30
dtype: int64

In [4]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

In [5]:
# --------------------------------     DATAFRAMES      -------------------

In [7]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [8]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns =columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [22]:
df2[["Name","Age"]]

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [10]:
df2["designation"] = ["Doc","Engg","pilot","teacher"]

In [11]:
df2

    Name  Age      City  Salary designation
0   John   28  New York   65000         Doc
1   Anna   34     Paris   70000        Engg
2  Peter   29    Berlin   62000       pilot
3  Linda   42    London   85000     teacher

In [16]:
# df2.drop("Name",axis = 1)
df2.drop(0,axis = 0)

    Name  Age    City  Salary designation
1   Anna   34   Paris   70000        Engg
2  Peter   29  Berlin   62000       pilot
3  Linda   42  London   85000     teacher

In [18]:
df2.loc[[0,2]]
# specific indexes hi dega no range

    Name  Age      City  Salary designation
0   John   28  New York   65000         Doc
2  Peter   29    Berlin   62000       pilot

In [20]:
df2

    Name  Age      City  Salary designation
0   John   28  New York   65000         Doc
1   Anna   34     Paris   70000        Engg
2  Peter   29    Berlin   62000       pilot
3  Linda   42    London   85000     teacher

In [19]:
df2.iloc[3]

Name             Linda
Age                 42
City            London
Salary           85000
designation    teacher
Name: 3, dtype: object

In [26]:
# selecting subsets
df2.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [27]:
# --------------------conditional selection----------------------------

In [28]:
df2

    Name  Age      City  Salary designation
0   John   28  New York   65000         Doc
1   Anna   34     Paris   70000        Engg
2  Peter   29    Berlin   62000       pilot
3  Linda   42    London   85000     teacher

In [29]:
df2[df2["Age"] > 30]

    Name  Age    City  Salary designation
1   Anna   34   Paris   70000        Engg
3  Linda   42  London   85000     teacher

In [33]:
df2[(df2["Age"] > 30) & (df2["City"] == "Paris")]

   Name  Age   City  Salary designation
1  Anna   34  Paris   70000        Engg